# Generated by Django 4.2.1 on 2023-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(default='', max_length=10, unique=True)),
                ('driver_name', models.CharField(default='', max_length=30)),
                ('driver_email', models.CharField(max_length=50)),
                ('taxi_num', models.CharField(max_length=10, unique=True)),
                ('driver_phone', models.CharField(max_length=11)),
                ('driver_test_date', models.DateField(max_length=12)),
                ('driver_pollution_validity', models.DateField(max_length=12)),
                ('driver_insurance', models.DateField(max_length=12)),
            ],
        ),
    ]
