# Generated by Django 4.2.1 on 2023-05-07 02:12

from api.models import unique_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_insurance',
            new_name='taxi_insurance',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_pollution_validity',
            new_name='taxi_pollution_validity',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_test_date',
            new_name='taxi_test_date',
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(default='available', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_upi',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='taxi_model',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='taxi_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(default=unique_generator.generate_unique_code_for_driverid, max_length=10, unique=True),
        ),
    ]
