# Generated by Django 4.2.1 on 2023-05-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_driver_insurance_driver_taxi_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('start_from', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('requested_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
