# Generated by Django 4.2 on 2023-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ride_rideid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='carpoolPercent',
            field=models.IntegerField(default=0),
        ),
    ]
