# Generated by Django 4.2 on 2023-06-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_earnings_newdriver_newridedetails_taxidetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdriver',
            name='taxi_num',
        ),
    ]
