# Generated by Django 4.2 on 2023-06-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_newdriver_taxi_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Earnings',
            new_name='Earning',
        ),
        migrations.RenameModel(
            old_name='NewRideDetails',
            new_name='NewRideDetail',
        ),
        migrations.RenameModel(
            old_name='TaxiDetails',
            new_name='TaxiDetail',
        ),
    ]
