# Generated by Django 4.2 on 2023-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_earnings_earning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdriver',
            name='driver_dob',
            field=models.DateField(),
        ),
    ]
