# Generated by Django 4.2 on 2023-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_newdriver_driver_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdriver',
            name='driver_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='newdriver',
            name='driver_upi',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
