# Generated by Django 4.2.2 on 2023-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_newdriver_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdriver',
            name='driver_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='newdriver',
            name='driver_id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newdriver',
            name='driver_phone',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='newdriver',
            name='driver_status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
