# Generated by Django 4.2 on 2023-06-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_newdriver_driver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newridedetail',
            name='driver_name',
        ),
        migrations.AlterField(
            model_name='newdriver',
            name='driver_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
