# Generated by Django 4.2 on 2023-06-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_newridedetail_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newridedetail',
            name='driver_name',
            field=models.CharField(default='we', max_length=100),
            preserve_default=False,
        ),
    ]
