# Generated by Django 4.2 on 2023-06-21 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_newridedetail_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newridedetail',
            name='driver_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.newdriver'),
        ),
    ]
