# Generated by Django 4.2 on 2023-06-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_newdriver_driver_email_and_more'),
        ('api', '0016_newridedetail_driver_id_and_more'),
    ]

    operations = [
    ]
