# Generated by Django 5.0.6 on 2024-05-09 14:17

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20230623_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='yellow_tripdata_2016_03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorID', models.IntegerField()),
                ('tpep_pickup_datetime', models.DateTimeField()),
                ('tpep_dropoff_datetime', models.DateTimeField()),
                ('passenger_count', models.IntegerField()),
                ('trip_distance', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('pickup_latitude', models.FloatField()),
                ('RatecodeID', models.IntegerField()),
                ('store_and_fwd_flag', models.CharField(max_length=1)),
                ('dropoff_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('payment_type', models.IntegerField()),
                ('fare_amount', models.FloatField()),
                ('extra', models.FloatField()),
                ('mta_tax', models.FloatField()),
                ('tip_amount', models.FloatField()),
                ('tolls_amount', models.FloatField()),
                ('improvement_surcharge', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='newridedetail',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='newridedetail',
            name='expectedReachingtime',
        ),
        migrations.AddField(
            model_name='newridedetail',
            name='passenger_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxidetail',
            name='driver_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.newdriver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='earning',
            name='driver_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.newdriver'),
        ),
        migrations.AlterField(
            model_name='newdriver',
            name='driver_dob',
            field=models.DateField(max_length=12),
        ),
        migrations.AlterField(
            model_name='newdriver',
            name='driver_phone',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='driver_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.newdriver'),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='expectedDriverPay',
            field=models.IntegerField(default=0, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='reachedtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='rideId',
            field=models.IntegerField(default=api.models.unique_generator.generate_unique_code_for_rideid, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='starting_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='status',
            field=models.CharField(default='requested', max_length=20),
        ),
    ]
