# Generated by Django 5.0.6 on 2024-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_yellow_tripdata_2016_03_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yellow_tripdata_2016_03',
        ),
    ]
