# Generated by Django 5.0.6 on 2024-05-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_yellow_tripdata_2016_03'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newridedetail',
            name='driver_id',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.newdriver'),
        ),
    ]
