# Generated by Django 5.0.6 on 2024-05-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_newridedetail_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newridedetail',
            name='driver_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.newdriver'),
        ),
    ]
